tasks/urls.py
from django.urls import path
from .views import create_task, show_my_tasks

app_name = "tasks"

urlpatterns = [
    path("create/", create_task, name="create_task"),
    path("mine/", show_my_tasks, name="show_my_tasks"),
]

teams/urls.py
from django.urls import path
from django.shortcuts import redirect
from .views import (
    team_list,
    create_team,
    show_my_teams,
    create_team_project,
    create_team_member,
)

app_name = "teams"


def my_teams_redirect_view(request):
    return redirect("teams:list_teams")


urlpatterns = [
    path("", team_list, name='list_teams'),
    path("create/", create_team, name='create_team'),
    path('<int:team_id>/', show_my_teams, name='show_my_teams'),
    path('<int:team_id>/create_team_project/', create_team_project,
         name='create_project'),
    path('<int:team_id>/create_team_member/', create_team_member,
         name='add_member'),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


def my_redirect_view(request):
    return redirect("projects:home")


urlpatterns = [
    path("", my_redirect_view, name="home"),
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls", namespace="projects")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("teams/", include("teams.urls", namespace="teams")),
]

teams/models.py
from django.db import models
from django.contrib.auth.models import User
from projects.models import Project


class Team(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(
        max_length=200,
        default=None,
        )
    members = models.ManyToManyField(User)
    projects = models.ManyToManyField(Project)

    def __str__(self):
        return self.name


class TeamProject(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(
        max_length=200,
        default=None,
        )
    team = models.ForeignKey(
        Team,
        on_delete=models.CASCADE,
        related_name="team_projects",
        null=True,
        )

    def __str__(self):
        return self.name


class TeamMember(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    username = models.CharField(max_length=100)
    email = models.EmailField(max_length=200)
    role = models.CharField(max_length=100)

    def __str__(self):
        return self.username

teams/forms.py
from django import forms
from .models import Team, TeamProject


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ['name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class TeamProjectForm(forms.ModelForm):
    class Meta:
        model = TeamProject
        fields = ['name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }


class TeamMemberForm(forms.Form):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    username = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)
    role = forms.CharField(max_length=100, required=True)

teams/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Team, TeamMember
from .forms import (
    TeamForm,
    TeamProjectForm,
    TeamMemberForm,
)


@login_required
def team_list(request):
    if request.method == 'POST':
        form = TeamForm(request.POST)
        if form.is_valid():
            team = form.save(commit=False)
            team.save()
            team.members.add(request.user)
            return redirect("teams_home")
    else:
        form = TeamForm()
    teams = Team.objects.all()
    context = {
        'teams': teams,
        'form': form
        }
    return render(request, 'teams/list.html', context)


@login_required
def create_team(request):
    if request.method == 'POST':
        form = TeamForm(request.POST)
        if form.is_valid():
            team = form.save(commit=False)
            team.owner = request.user
            team.save()
            team.members.add(request.user)
            return redirect('list_teams', team_id=team.id)
    else:
        form = TeamForm()
    context = {'form': form}
    return render(request, 'teams/create.html', context)


@login_required
def show_my_teams(request, team_id):
    team = get_object_or_404(Team, id=team_id)
    context = {
        'team': team
        }
    return render(request, 'teams/detail.html', context)


@login_required
def create_team_project(request, team_id):
    team = get_object_or_404(Team, id=team_id)
    if request.method == 'POST':
        form = TeamProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.team = team
            project.save()
            project.members.add(request.user)
            return redirect('show_team', team_id=team.id)
    else:
        form = TeamProjectForm()
    context = {
        'form': form
        }
    return render(request, 'teams/create_team_project.html', context)


def create_team_member(request):
    if request.method == 'POST':
        form = TeamMemberForm(request.POST)
        if form.is_valid():
            # Create a new TeamMember object with the submitted data
            member = TeamMember(
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                username=form.cleaned_data['username'],
                email=form.cleaned_data['email'],
                role=form.cleaned_data['role']
            )
            member.save()
            return redirect('show_team', member_id=member.id)
    else:
        form = TeamMemberForm()
    context = {
        'form': form
    }
    return render(request, 'teams/create_team_member.html', context)

teams/templates/teams/create.html
{% extends 'base.html' %}

{% block title %}
    Teams App - Teams Create View
{% endblock title %}


{% block content %}
  <h1>Create Team Project</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
  </form>
{% endblock content %}

teams/templates/teams/create_team_member.html
{% extends 'base.html' %}

{% block title %}
    Teams App - Teams Team Members Add View
{% endblock title %}


{% block content %}
  <h1>Add a member to your team</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
  </form>
{% endblock content %}

teams/templates/teams/create_team_project.html
{% extends 'base.html' %}

{% block title %}
    Teams App - Teams Create Team Project View
{% endblock title %}

{% block content %}
  <h1>Create Project for {{ team.name }}</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Create Team Project</button>
  </form>
{% endblock %}

teams/templates/teams/detail.html
{% extends "base.html" %}


{% block title %}
    Teams App - Teams Detail View
{% endblock title %}

{% block content %}
  <h1>{{ team.name }}</h1>
  <h2>Members:</h2>
  <p>
    <a href="{% url 'teams:create_team_member' team.id %}">Add Member</a>
    <a href="{% url 'teams:create_team_project' team.id %}">Create Team Project</a>
  </p>
  <ul>
    {% for member in team.members.all %}
      <li>{{ member.username }}</li>
    {% endfor %}
  </ul>
  <h2>Projects:</h2>
  <ul>
    {% for project in team.projects.all %}
      <li>{{ project.name }}</li>
      <p>{{ project.description }}</p>
      <p>Members:</p>
      <ul>
        {% for member in project.members.all %}
          <li>{{ member.username }}</li>
        {% endfor %}
      </ul>
    {% endfor %}
  </ul>
{% endblock content %}

teams/templates/teams/list.html
{% extends 'base.html' %}

{% block title %}
    Teams App - Teams List View
{% endblock title %}

{% block content %}
  <h1>My Teams</h1>
  <ul>
    {% for team in teams %}
      <li><a href="{% url "teams:show_my_team" team_id=team.id %}">{{ team.name }}</a></li>
    {% endfor %}
  </ul>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"><a href="{% url "teams:create_team" %}">Create Team</button>
  </form>
{% endblock %}