accounts/urls.py
from django.urls import path
from .views import (
    user_login,
    user_logout,
    user_signup,
)

app_name = "accounts"

urlpatterns = [
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
    path("signup/", user_signup, name="signup"),
]

projects/urls.py
from django.urls import path
from .views import (
    project_list,
    show_project,
    create_project,
)

app_name = "projects"

urlpatterns = [
    path("", project_list, name="home"),
    path("create/", create_project, name="create_project"),
    path("<int:id>/", show_project, name="show_project"),
]

tasks/urls.py
from django.urls import path
from .views import create_task, show_my_tasks

app_name = "tasks"

urlpatterns = [
    path("create/", create_task, name="create_task"),
    path("mine/", show_my_tasks, name="show_my_tasks"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


def my_redirect_view(request):
    return redirect("projects:home")


urlpatterns = [
    path("", my_redirect_view, name="home"),
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls", namespace="projects")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("teams/", include("teams.urls", namespace="teams")),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=None)
    owner = models.ForeignKey(
        User,
        related_name="projects",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.name

projects/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = [
            "name",
            "description",
            "owner",
        ]

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Project
from .forms import ProjectForm
from django.contrib.auth.decorators import login_required


@login_required
def project_list(request):
    projects = Project.objects.filter(owner=request.user)
    context = {
        "projects": projects,
    }
    return render(request, "projects/list.html", context)


@login_required
def show_project(request, id):
    project = get_object_or_404(Project, id=id)
    tasks = project.tasks.all()
    context = {
        "project": project,
        "tasks": tasks,
    }
    return render(request, "projects/detail.html", context)


@login_required
def create_project(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.owner = request.user
            project.save()
            return redirect("home")
    else:
        form = ProjectForm()
        context = {
            "form": form,
        }
    return render(request, "projects/create.html", context)

projects/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="project and task manager application"
              content="It's composed of projects, tasks, and the ability to log in, log out, and sign up for the application. ">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="keywords"
              content="project management, task management, login, logout, signup, application">
        <link rel="stylesheet"
              type="text/css"
              href="{% static 'css/apps.css' %}">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'teams:list_teams' %}">My teams</a>
                        </li>
                        <li>
                            <a href="{% url 'projects:home' %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url 'tasks:show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>