projects/urls.py
from django.urls import path
from .views import (
    project_list,
    show_project,
    create_project,
)

app_name = "projects"

urlpatterns = [
    path("", project_list, name="home"),
    path("create/", create_project, name="create_project"),
    path("<int:id>/", show_project, name="show_project"),
]

tasks/urls.py
from django.urls import path
from .views import create_task, show_my_tasks

app_name = "tasks"

urlpatterns = [
    path("create/", create_task, name="create_task"),
    path("mine/", show_my_tasks, name="show_my_tasks"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


def my_redirect_view(request):
    return redirect("projects:home")


urlpatterns = [
    path("", my_redirect_view, name="home"),
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls", namespace="projects")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("teams/", include("teams.urls", namespace="teams")),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=None)
    owner = models.ForeignKey(
        User,
        related_name="projects",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.name

projects/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = [
            "name",
            "description",
            "owner",
        ]

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Project
from .forms import ProjectForm
from django.contrib.auth.decorators import login_required


@login_required
def project_list(request):
    projects = Project.objects.filter(owner=request.user)
    context = {
        "projects": projects,
    }
    return render(request, "projects/list.html", context)


@login_required
def show_project(request, id):
    project = get_object_or_404(Project, id=id)
    tasks = project.tasks.all()
    context = {
        "project": project,
        "tasks": tasks,
    }
    return render(request, "projects/detail.html", context)


@login_required
def create_project(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.owner = request.user
            project.save()
            return redirect("home")
    else:
        form = ProjectForm()
        context = {
            "form": form,
        }
    return render(request, "projects/create.html", context)

projects/templates/projects/create.html
{% extends "base.html" %}

{% block title %}
    Projects App - Projects CreateView
{% endblock title %}
{% block content %}
    <main>
        <div class="project-form">
            <h1>Create a new project</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

projects/templates/projects/detail.html
{% extends "base.html" %}

{% block title %}
    Projects App - Projects DetailView
{% endblock title %}
{% block content %}
    <main>
        <div class="project-detail">
            <h1>{{ project.name }}</h1>
            <p>{{ project.description }}</p>
            <h2>Tasks</h2>
            <p>
                <a href="{% url "tasks:create_task" %}">Create a new task</a>
            </p>
            {% if tasks %}
                <table>
                    <thread>
                    <tr>
                        <th>Name</th>
                        <th>Assignee</th>
                        <th>Start date</th>
                        <th>Due date</th>
                        <th>Is completed</th>
                    </tr>
                    </thread>
                    <tbody>
                        {% for task in tasks %}
                            <tr>
                                <td>{{ task.name }}</td>
                                <td>{{ task.assignee }}</td>
                                <td>{{ task.start_date }}</td>
                                <td>{{ task.due_date|default:"N/A" }}</td>
                                <td>{{ task.is_completed|yesno:"Yes,No" }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>This project has no tasks</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/list.html
{% extends "base.html" %}

{% block title %}
    Projects App - Projects ListView - HOME
{% endblock title %}
{% block content %}
    <main>
        <div class="project-list">
            <h1>My Projects</h1>
            <p>
                <a href="{% url "projects:create_project" %}">Create a new project</a>
            </p>
            {% if projects %}
                <table>
                    <thread>
                    <tr>
                        <th>Name</th>
                        <th>Number of tasks</th>
                    </tr>
                    </thread>
                    <tbody>
                        {% for project in projects %}
                            <tr>
                                <td>
                                    <a href="{% url "projects:show_project" id=project.id %}">{{ project.name }}</a>
                                </td>
                                <td>{{ project.tasks.all|length }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>You are not assigned to any projects</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}